name: Best CAF Kernel

on:
  workflow_dispatch:

jobs:
  build:
    name: Finding Best CAF Kernel
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing environment
         run: |
            git config --global user.name "jun10r4lm31d4"
            git config --global user.email "jun10r4lm31d4@outlook.com"
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex curl bison aria2

       - name: Sync kernel source
         run: |
             chmod 777 config.sh
             source config.sh
             git clone --depth=1 $KERNEL_SOURCE -b $BRANCH source

       - name: fetching caf sources
         run: |
              chmod 777 config.sh
              source config.sh
              cd source
              git fetch https://git.codelinaro.org/clo/la/kernel/$KERNEL_VERSION 'refs/tags*:refs/tags*'

       - name: Finding best caf tag
         run: |
              chmod 777 config.sh
              source config.sh
              cd source
              wget https://raw.githubusercontent.com/LineageOS/scripts/master/best-caf-kernel/best-caf-kernel.py
              chmod +x best-caf-kernel.py
              python best-caf-kernel.py "$PLATFORM"
